language: objective-c
osx_image: xcode9.2
rvm:
- 2.2
env:
  global:
# safelist
branches:
  only:
  - master
  - stable
cache:
  directories:
  - "$UNITY_DOWNLOAD_CACHE"
before_install:
- chmod a+x ./travisScripts/install.sh
- chmod a+x ./travisScripts/build.sh
install:
- ./travisScripts/install.sh
script:
- ./travisScripts/build.sh
